#!/bin/bash
########################################################################
#                                                                      #
# backup                                                               #
# Automate rotating rsync backups to offline devices                   #
#                                                                      #
# Credit to Mike Rubel for describing the process.                     #
# http://www.mikerubel.org/computers/rsync_snapshots/                  #
#                                                                      #
# The process in this script differers from most rotating rsync        #
# scripts because it makes no attempt to rotate checkpoints in a       #
# hierarchal manner. Simply, if the most recent checkpoint of a type   #
# is older than expected, the checkpoints are rotated and a new one is #
# created.                                                             #
#                                                                      #
########################################################################
IFS=' '
PATH=/usr/sbin:/usr/bin:/sbin:/bin

OK=YES
CONFIG='/etc/backup.conf'

if [[ -f "${CONFIG}" ]]; then
    . "${CONFIG}"
else
    echo "**** BACKUP CONFIGURATION FILE MISSING (${CONFIG}) ****" 1>&2
    echo '' 1>&2
    OK=NO
fi

[[ -v COMMENT ]] || COMMENT=''
[[ -v INSTANT ]] || INSTANT=24
[[ -v DAILY   ]] || DAILY=7
[[ -v WEEKLY  ]] || WEEKLY=4
[[ -v MONTHLY ]] || MONTHLY=12
[[ -v YEARLY  ]] || YEARLY=3

if ! [[ -v DEVICE ]]; then
    DEVICE=''
    echo '**** DEVICE IS NOT IS NOT CONFIGURED ****' 1>&2
    echo 'EXAMPLE:' 1>&2
    echo "DEVICE='/dev/disk/by-partlabel/partlabel'" 1>&2
    echo '' 1>&2
    OK=NO
fi

if ! [[ -v MOUNT ]]; then
    MOUNT=''
    echo '**** MOUNT IS NOT IS NOT CONFIGURED ****' 1>&2
    echo 'EXAMPLE:' 1>&2
    echo "MOUNT='/var/local/backup'" 1>&2
    echo '' 1>&2
    OK=NO
fi

if ! [[ -v HEAD ]]; then
    HEAD=''
    echo '**** HEAD IS NOT IS NOT CONFIGURED ****' 1>&2
    echo 'EXAMPLE:' 1>&2
    echo 'HEAD="${MOUNT}/`hostname`/head"' 1>&2
    echo '' 1>&2
    OK=NO
fi

if ! [[ -v RSYNC ]]; then
    RSYNC[0]=''
    echo '**** RSYNC ARRAY IS NOT IS NOT CONFIGURED ****' 1>&2
    echo 'EXAMPLE:' 1>&2
    echo '#'
    echo '# Remember, you probably do not want to use a trailing slash on the'
    echo '# rsync source path. Read the rsync documentation to understand why.'
    echo '#'
    echo 'RSYNC=(' 1>&2
    echo '    "rsync -a --delete --numeric-ids --relative --delete-excluded --hard-links /etc  ${HEAD}"' 1>&2
    echo '    "rsync -a --delete --numeric-ids --relative --delete-excluded --hard-links /home ${HEAD}"' 1>&2
    echo ')' 1>&2
    echo '' 1>&2
    OK=NO
fi

[[ -v ROOT ]] || ROOT=`dirname "${HEAD}"`
[[ -v DEVICE_REAL ]] || DEVICE_REAL=`readlink -f "${DEVICE}"`

########################################################################
fnConfig() {
    echo "COMMENT : ${COMMENT}"
    echo "INSTANT : ${INSTANT}"
    echo "DAILY   : ${DAILY}"
    echo "WEEKLY  : ${WEEKLY}"
    echo "MONTHLY : ${MONTHLY}"
    echo "YEARLY  : ${YEARLY}"
    echo "DEVICE  : ${DEVICE} (${DEVICE_REAL})"
    echo "MOUNT   : ${MOUNT}"
    echo "HEAD    : ${HEAD}"
}

fnHelp() {
    echo "${0} is a shell script that automates backups with rsync"
    echo 'The following options are available:'
    echo '  help              Show this message'
    echo '  start             Backup the filesystem'
    echo '  config            Show the current configuration'
    echo '  df                Display disk usage on backup device'
    echo '  du                Display space consumed by backups'
    echo '  diff              Dry-run with verbose output'
    echo '  ls                List all backups'
    echo '  mount [dir [rw]]  Mount the backup device'
    echo '  umount            Unmount the backup device'
}

fnIsAvailable() {
    [[ -b "${1}" ]]
    return $?
}

fnIsMounted() {
    grep -qs "^$1 " /proc/mounts
    return $?
}

fnMount() {
    local RESULT
    local MNT
    local OPT
    if [[ "$1" = "" ]]; then
        MNT="${MOUNT}"
        OPT="rw"
    else
        MNT="${1}"
        OPT="ro"

        if [[ "${2}" = "rw" ]]; then
            OPT="rw"
        fi
    fi

    if ! fnIsAvailable "${DEVICE_REAL}"; then
        echo "**** ${DEVICE} IS NOT AVAILABLE ****" 1>&2
        RESULT=1
    elif fnIsMounted "${DEVICE_REAL}"; then
        echo "**** ${DEVICE} IS ALREADY MOUNTED ****" 1>&2
        RESULT=1
    elif [[ ! -d "${MNT}" ]]; then
        echo "**** MOUNT POINT ${MNT} DOES NOT EXIST ****" 1>&2
        RESULT=1
    else
        echo "mount -o ${OPT} ${DEVICE_REAL} ${MNT}"
        mount -o "${OPT}" "${DEVICE_REAL}" "${MNT}"
        if [[ "$?" -ne "0" ]]; then
            echo '**** ERROR MOUNTING ${DEVICE} ****' 1>&2
            RESULT=1
        else
            RESULT=0
        fi
    fi
    return "${RESULT}"
}

fnUmount() {
    if ! fnIsMounted "${DEVICE_REAL}"; then
        echo "**** ${DEVICE} IS NOT MOUNTED ****" 1>&2
        return 1
    else
        echo "umount ${DEVICE_REAL}"
        umount "${DEVICE_REAL}"
        if [[ "$?" -ne "0" ]]; then
            echo '**** ERROR UNMOUNTING ${DEVICE} ****' 1>&2
            return 1
        else
            return 0
        fi
    fi
}

fnDf() {
    local RESULT
    if ! fnMount "${MOUNT}" ro; then
        RESULT=1
    else
        echo "df -h ${DEVICE_REAL}"
        df -h "${DEVICE_REAL}"
        RESULT=$?

        if ! fnUmount; then
            RESULT=1
        fi
    fi
    return "${RESULT}"
}

fnDu() {
    local RESULT
    if ! fnMount "${MOUNT}" ro; then
        RESULT=1
    else
        echo 'du -shc'
        {
            find "${HEAD}" -maxdepth 0 -type d                   -print 2>/dev/null
            find "${ROOT}" -maxdepth 1 -type d -name "instant.*" -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "daily.*"   -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "weekly.*"  -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "monthly.*" -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "yearly.*"  -print 2>/dev/null |sort
        } |xargs du -shc
        RESULT=$?

        if ! fnUmount; then
            RESULT=1
        fi
    fi
    return "${RESULT}"
}

fnLs() {
    local RESULT
    if ! fnMount "${MOUNT}" ro; then
        RESULT=1
    else
        echo 'du -shc'
        {
            find "${HEAD}" -maxdepth 0 -type d                   -print 2>/dev/null
            find "${ROOT}" -maxdepth 1 -type d -name "instant.*" -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "daily.*"   -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "weekly.*"  -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "monthly.*" -print 2>/dev/null |sort
            find "${ROOT}" -maxdepth 1 -type d -name "yearly.*"  -print 2>/dev/null |sort
        } |xargs ls -fld
        RESULT=$?

        if ! fnUmount; then
            RESULT=1
        fi
    fi
    return "${RESULT}"
}

fnDiff() {
    local RESULT=0
    local CMD

    if ! [[ -v DIFF ]]; then
        local N=0
        for CMD in "${RSYNC[@]}"; do
            DIFF["${N}"]=`echo "${CMD}" |sed 's/rsync /rsync -n -v /'`
            ((N++))
        done
    fi

    if ! fnMount "${MOUNT}" ro; then
        RESULT=1
    else
        for CMD in "${DIFF[@]}"; do
            echo "${CMD}"
            $CMD
            if [[ "$?" -ne "0" ]]; then
                RESULT=1
            fi
        done

        if ! fnUmount; then
            RESULT=1
        fi
    fi
    return "${RESULT}"
}

fnRotate() {
    local RPATH="${1}"
    local CNAME="${2}"
    local N="${3}"

    local BASE="${RPATH}/${CNAME}"
    local NEW
    local OLD

    while [[ "${N}" -gt "1" ]]; do
        printf -v NEW '%s.%02d' "${BASE}" "${N}"
        ((N--))
        printf -v OLD '%s.%02d' "${BASE}" "${N}"

        if [[ -d "${NEW}" ]]; then
            echo "rm -rf ${NEW}"
            rm -rf "${NEW}"
            if [[ "$?" -ne "0" ]]; then
                echo '**** ERROR REMOVING DIRECTORY ****' 1>&2
                return 1
            fi
        fi

        if [[ -d "${OLD}" ]]; then
            echo "mv -f ${OLD} ${NEW}"
            mv -f "${OLD}" "${NEW}"
            if [[ "$?" -ne "0" ]]; then
                echo '**** ERROR MOVING DIRECTORY ****' 1>&2
                return 1
            fi
        fi
    done
}

fnMkCheckpoint() {
    local PTNAME="${1}"
    local PTCNT="${2}"

    if [[ "${PTCNT}" -gt "0" ]]; then
        echo "-- CREATE CHECKPOINT ${PTNAME} --"
        fnRotate "${ROOT}" "${PTNAME}" "${PTCNT}"
        echo "cp -al ${HEAD} ${ROOT}/${PTNAME}.01"
        cp -al "${HEAD}" "${ROOT}/${PTNAME}.01"
    fi
}

fnStart() {
    local RESULT="0"
    if ! fnMount; then
        RESULT=1
    else
        if [[ -d "${ROOT}" ]]; then
            if [[ ! -d "${HEAD}" ]]; then
                echo "-- CREATE HEAD DIRECTORY --"
                echo "mkdir -m 0755 ${HEAD}"
                mkdir -m 0755 -p "${HEAD}"
            fi
        fi

        if [[ ! -d "${HEAD}" ]]; then
            echo "**** HEAD PATH NOT FOUND ${HEAD} ****" 1>&2
            RESULT=1
        else
            local D=`find "${ROOT}/daily.01"   -maxdepth 0 -type d -mmin  +1430 2>/dev/null`
            local W=`find "${ROOT}/weekly.01"  -maxdepth 0 -type d -mtime +6    2>/dev/null`
            local M=`find "${ROOT}/monthly.01" -maxdepth 0 -type d -mtime +29   2>/dev/null`
            local Y=`find "${ROOT}/yearly.01"  -maxdepth 0 -type d -mtime +364  2>/dev/null`

            echo "-- RUNNING BACKUP COMMANDS --"
            local CMD
            for CMD in "${RSYNC[@]}"; do
                echo "${CMD}"
                $CMD
                if [[ "$?" -ne "0" ]]; then
                    RESULT=1
                fi
            done

            if [[ "${RESULT}" -ne "0" ]]; then
                echo '**** ERROR RUNNING BACKUP ****' 1>&2
                RESULT=1
            else
                echo "touch ${HEAD}"
                touch "${HEAD}"

                fnMkCheckpoint instant "${INSTANT}"

                if [[ ! -d "${ROOT}/daily.01" || -n "${D}" ]]; then 
                    fnMkCheckpoint daily "${DAILY}"
                fi

                if [[ ! -d "${ROOT}/weekly.01" || -n "${W}" ]]; then 
                    fnMkCheckpoint weekly "${WEEKLY}"
                fi

                if [[ ! -d "${ROOT}/monthly.01" || -n "${M}" ]]; then 
                    fnMkCheckpoint monthly "${MONTHLY}"
                fi

                if [[ ! -d "${ROOT}/yearly.01" || -n "${Y}" ]]; then 
                    fnMkCheckpoint yearly "${YEARLY}"
                fi

                RESULT=$?
            fi

            echo 'sync; sync;'
            sync; sync;
        fi

        if ! fnUmount; then
            RESULT=1
        fi
    fi
    return "${RESULT}"
}

fnDashes() {
    local LEN="${1}"
    printf '%*s' ${LEN} |tr ' ' '-'
}

fnSpaces() {
    local LEN="${1}"
    printf '%*s' ${LEN}
}

fnPrintComment() {
    if [[ -n "${COMMENT}" ]]; then
        local C=80
        local S=''
        local D=`fnDashes "${#COMMENT}"`

        #if [[ ${C} -gt ${#COMMENT} ]]; then
        #    S=`fnSpaces $(( ( ${C} - ${#COMMENT} ) / 2 ))`
        #fi

        echo "${S}${D}"
        echo "${S}${COMMENT}"
        echo "${S}${D}"
    fi
}

########################################################################

if [[ "${OK}" != "YES" ]]; then
    fnConfig
    exit 1
fi

case "$1" in
    start)
        fnPrintComment
        fnStart
        exit $?
        ;;
    help)
        fnHelp
        exit 0
        ;;
    config)
        fnConfig
        exit 0
        ;;
    df)
        fnPrintComment
        fnDf
        exit $?
        ;;
    du)
        fnPrintComment
        fnDu
        exit $?
        ;;
    diff)
        fnPrintComment
        fnDiff
        exit $?
        ;;
    ls)
        fnPrintComment
        fnLs
        exit $?
        ;;
    mount)
        fnPrintComment
        fnMount "${2}" "${3}"
        exit $?
        ;;
    umount)
        fnPrintComment
        fnUmount
        exit $?
        ;;
    *)
        fnHelp
        exit 1
        ;;
esac
